modLoader = "javafml"
loaderVersion = "[45,)"
issueTrackerURL = "https://github.com/TeamDiopside/Seamless/issues"
license = "MIT"

[[mods]]
modId = "seamless"
version = "${version}"
displayName = "Seamless"
authors = "LarsMans"
description = '''
A mod that connects the outlines of Double Blocks, like Doors and Beds.
'''
logoFile = "../modicon.png"

[[dependencies.seamless]]
modId = "forge"
mandatory = true
versionRange = "[45,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.seamless]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.3,1.19.4]"
ordering = "NONE"
side = "BOTH"

[[dependencies.seamless]]
modId = "architectury"
mandatory = true
versionRange = "[8.2.89,)"
ordering = "AFTER"
side = "BOTH"