modLoader = "javafml"
loaderVersion = "[48,)"
issueTrackerURL = "https://github.com/TeamDiopside/Seamless/issues"
license = "MIT"

[[mods]]
modId = "seamless"
version = "${version}"
displayName = "Seamless"
authors = "LarsMans"
description = '''
A Fabric/Forge mod that connects the outlines of Double Blocks, like Doors and Beds.
'''
logoFile = "../modicon.png"

[[dependencies.seamless]]
modId = "forge"
mandatory = true
versionRange = "[48,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.seamless]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.seamless]]
modId = "architectury"
mandatory = true
versionRange = "[10.0.8,)"
ordering = "AFTER"
side = "BOTH"