modLoader = "javafml"
loaderVersion = "[45,)"
issueTrackerURL = "https://github.com/TeamDiopside/Seamless/issues"
license = "MIT"

[[mods]]
modId = "seamless"
version = "${version}"
displayName = "Seamless"
authors = "LarsMans"
description = '''
A Fabric/Forge mod that connects the outlines of Double Blocks, like Doors and Beds.
'''
logoFile = "../../../../common/src/main/resources/assets/seamless/icon.png"

[[dependencies.examplemod]]
modId = "forge"
mandatory = true
versionRange = "[45,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.examplemod]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.examplemod]]
modId = "architectury"
mandatory = true
versionRange = "[8.1.79,)"
ordering = "AFTER"
side = "BOTH"