modLoader = "javafml"
loaderVersion = "[41,)"
issueTrackerURL = "https://github.com/TeamDiopside/Seamless/issues"
license = "MIT"

[[mods]]
modId = "seamless"
version = "${version}"
displayName = "Seamless"
authors = "LarsMans"
description = '''
A Fabric/Forge mod that connects the outlines of Double Blocks, like Doors and Beds.
'''
logoFile = "icon.png"

[[dependencies.seamless]]
modId = "forge"
mandatory = true
versionRange = "[41,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.seamless]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.seamless]]
modId = "architectury"
mandatory = true
versionRange = "[5.14.76,)"
ordering = "AFTER"
side = "BOTH"