modLoader = "javafml"
loaderVersion = "[38,)"
issueTrackerURL = "https://github.com/TeamDiopside/Seamless/issues"
license = "MIT"

[[mods]]
modId = "seamless"
version = "${version}"
displayName = "Seamless"
authors = "LarsMans"
description = '''
A mod that connects the outlines of Double Blocks, like Doors and Beds.
'''
logoFile = "../modicon.png"

[[dependencies.seamless]]
modId = "forge"
mandatory = true
versionRange = "[38,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.seamless]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,1.18.2]"
ordering = "NONE"
side = "BOTH"

[[dependencies.seamless]]
modId = "architectury"
mandatory = true
versionRange = "[3.9.66,)"
ordering = "AFTER"
side = "BOTH"