modLoader = "javafml"
loaderVersion = "[46,)"
issueTrackerURL = "https://github.com/TeamDiopside/Seamless/issues"
license = "MIT"

[[mods]]
modId = "seamless"
version = "${version}"
displayName = "Seamless"
authors = "LarsMans"
description = '''
A Fabric/Forge mod that connects the outlines of Double Blocks, like Doors and Beds.
'''
logoFile = "../modicon.png"

[[dependencies.seamless]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.seamless]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,1.20.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.seamless]]
modId = "architectury"
mandatory = true
versionRange = "[9.1.12,)"
ordering = "AFTER"
side = "BOTH"